### ISSUE TITLE
Gebruik hier ook een fallback

### ISSUE THREAD

**Issue by KrijnHoetmer** [MarsGotBars/fix-the-flow-interactive-website#7]
Je feature detect nu goed of `document.startViewTransition` bestaat, maar je hebt (nog) geen `else`, voor browsers die dit niet ondersteunen. Daar kun je gewoon `loadArticles()` aanroepen. Misschien meer wat voor Sprint 9, maar aangezien je hier nu al mee bezig bent.. :)

https://github.com/MarsGotBars/fix-the-flow-interactive-website/blob/21f5821a2294010cf65498ace6a2d57484f1d846/scripts/script.js#L47C71-L47C83

**Comment by KrijnHoetmer** [comment]
Niet helemaal duidelijk wat je in deze commit gedaan hebt, en of het hiermee opgelost is. Volgens mij in ieder geval veel meer dan waar dit issue over gaat. Duik echt eens in [Partial commits](https://github.blog/news-insights/product-news/partial-commits-in-github-for-windows/) om beter inzichtelijk te maken wat je aan het doen bent.

**Comment by MarsGotBars** [comment]
> Niet helemaal duidelijk wat je in deze commit gedaan hebt, en of het hiermee opgelost is. Volgens mij in ieder geval veel meer dan waar dit issue over gaat. Duik echt eens in [Partial commits](https://github.blog/news-insights/product-news/partial-commits-in-github-for-windows/) om beter inzichtelijk te maken wat je aan het doen bent.

Yes zal ik aan werken, gister zat ik heel gefocused te werken aan 'de laatste stukjes van het project' zeker niet aan partial commits gedacht.

Kort samengevat heb ik geen gebruik gemaakt van view transitions, dus had ik deze issue gesloten.

**Comment by KrijnHoetmer** [comment]
Hah, had je commit message niet goed gelezen :) No worries!
